networks:
  dbnet:
    name: dbnet
    driver: bridge

services:
  db1:
    image: postgres:15
    container_name: pg1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: demo1
    ports:
      - "5432:5432"
    networks:
      - dbnet

  db2:
    image: postgres:15
    container_name: pg2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass2
      POSTGRES_DB: demo2
    ports:
      - "5433:5432"
    networks:
      - dbnet